sonar.projectKey=chamsamalini_django
sonar.projectName=django
sonar.organization=chamsamalini2026
sonar.sources=banking_project,banking
sonar.tests=banking/tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/migrations/**,**/.venv/**,**/.venv.broken/**
